/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.database

import androidx.room3.Room
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import kotlinx.coroutines.Dispatchers
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppDatabaseTest {

    private var database: AppDatabase? = null

    @AfterTest
    fun teardown() {
        database?.close()
    }

    @Test
    fun inMemoryDatabaseCanBeCreated() {
        database = Room.inMemoryDatabaseBuilder<AppDatabase>()
            .setDriver(BundledSQLiteDriver())
            .setQueryCoroutineContext(Dispatchers.IO)
            .build()

        assertNotNull(database)
    }

    @Test
    fun databaseExposeTransactionDao() {
        database = Room.inMemoryDatabaseBuilder<AppDatabase>()
            .setDriver(BundledSQLiteDriver())
            .setQueryCoroutineContext(Dispatchers.IO)
            .build()

        assertNotNull(database!!.transactionDao)
    }

    @Test
    fun databaseExposeTransferDetailDao() {
        database = Room.inMemoryDatabaseBuilder<AppDatabase>()
            .setDriver(BundledSQLiteDriver())
            .setQueryCoroutineContext(Dispatchers.IO)
            .build()

        assertNotNull(database!!.transferDetailDao)
    }

    @Test
    fun databaseVersionIsCurrent() {
        // Fork wallet schema, currently at 9 — the transfer-detail Store5 vertical added
        // wallet_transfer_details via AutoMigration(7→8), and AutoMigration(8→9) follows it.
        // This guards the FORK's AppDatabase, not the upstream template demo database
        // (whose own version advances independently). Update this constant when bumping
        // AppDatabase.VERSION so the guardrail stays meaningful.
        assertEquals(9, AppDatabase.VERSION)
    }

    @Test
    fun databaseNameIsCorrect() {
        // Fork-unique, appId-derived (regenerated by syncForkConfig). DATABASE_NAME
        // delegates to the single source of truth, DatabaseConfig.NAME.
        assertEquals(DatabaseConfig.NAME, AppDatabase.DATABASE_NAME)
    }
}
